# User Test
#------------------------------------
APP              = test
# App sources
APP_SRCS         = exo1.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       =
# Linker flags
APP_LDFLAGS      =
PMSIS_OS = freertos
# Custom linker
APP_LINK_SCRIPT  =

include /home/osboxes/test-C/gap_sdk/utils/rules/pmsis_rules.mk
